export const FRAMEWORK_CATEGORY_NAMES = {
    ORM: "ORM",
    WEB_FRAMEWORK: "WEB_FRAMEWORK",
    HTTP_CLIENT: "HTTP_CLIENT",
    VALIDATION: "VALIDATION",
    DI_CONTAINER: "DI_CONTAINER",
    LOGGER: "LOGGER",
    CACHE: "CACHE",
    MESSAGE_QUEUE: "MESSAGE_QUEUE",
    EMAIL: "EMAIL",
    STORAGE: "STORAGE",
    TESTING: "TESTING",
    TEMPLATE_ENGINE: "TEMPLATE_ENGINE",
} as const

export const FRAMEWORK_CATEGORY_DESCRIPTIONS = {
    [FRAMEWORK_CATEGORY_NAMES.ORM]: "Database ORM/ODM",
    [FRAMEWORK_CATEGORY_NAMES.WEB_FRAMEWORK]: "Web Framework",
    [FRAMEWORK_CATEGORY_NAMES.HTTP_CLIENT]: "HTTP Client",
    [FRAMEWORK_CATEGORY_NAMES.VALIDATION]: "Validation Library",
    [FRAMEWORK_CATEGORY_NAMES.DI_CONTAINER]: "DI Container",
    [FRAMEWORK_CATEGORY_NAMES.LOGGER]: "Logger",
    [FRAMEWORK_CATEGORY_NAMES.CACHE]: "Cache",
    [FRAMEWORK_CATEGORY_NAMES.MESSAGE_QUEUE]: "Message Queue",
    [FRAMEWORK_CATEGORY_NAMES.EMAIL]: "Email Service",
    [FRAMEWORK_CATEGORY_NAMES.STORAGE]: "Storage Service",
    [FRAMEWORK_CATEGORY_NAMES.TESTING]: "Testing Framework",
    [FRAMEWORK_CATEGORY_NAMES.TEMPLATE_ENGINE]: "Template Engine",
} as const

export const DEFAULT_FRAMEWORK_CATEGORY_DESCRIPTION = "Framework Package"
